os: linux
language: python
dist: xenial
python:
- 3.7
- 3.8-dev
addons:
  apt:
    sources:
    - llvm-toolchain-xenial-5.0
    packages:
    - clang-5.0
    - mingw-w64-i686-dev
    - mingw-w64-x86-64-dev

matrix:
  include:
  - os: osx
    language: generic
    python: 3.7
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.7/Install\ Certificates.command
    - brew install mingw-w64
    - export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin"
  allow_failures:
  - python: "3.8-dev"

install:
- pip3 install --verbose .
script:
- wa -v --debug test 'http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A' -- echo 'Hello World'
- wa -v --debug submit 'http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A' C solutions/judge.u-aizu.ac.jp/ITP1_1_A.c
- wa -v --debug submit 'https://leetcode.com/problems/powx-n/' c examples/leetcode.com/powx-n.c
- wa -v --debug submit 'http://poj.org/problem?id=1000' 1 examples/poj.org/1000.c
- ./c.py -v --debug test solutions
- ./c.py -v --debug test --mode release solutions
- ./c.py -v --debug submit solutions
- ./c.py -v --debug submit examples
cache:
  pip: true
