os: linux
language: python
python:
- 3.6
- 3.7-dev
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - mingw-w64-i686-dev
    - mingw-w64-x86-64-dev

matrix:
  include:
  - os: windows
    language: sh
    before_install:
    - choco install python
  - os: osx
    language: generic
    python: 3.6
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.6.6/python-3.6.6-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.6/Install\ Certificates.command
    - brew install mingw-w64
    - export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin"
  allow_failures:
  - python: "3.7-dev"

install:
- pip3 install --verbose .
script:
- wa 'http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A' -v --debug --timestamps test -- echo 'Hello World'
- wa 'http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_1_A' -v --debug --timestamps submit C solutions/judge.u-aizu.ac.jp/ITP1_1_A.c
- wa 'https://leetcode.com/problems/powx-n/' -v --debug --timestamps submit c examples/leetcode.com/powx-n.c
- wa 'http://poj.org/problem?id=1000' -v --debug --timestamps submit 1 examples/poj.org/1000.c
- ./c.py -v --debug --timestamps test solutions
- ./c.py -v --debug --timestamps test --mode release solutions
- ./c.py -v --debug --timestamps submit solutions
- ./c.py -v --debug --timestamps submit examples
cache:
  pip: true
